"use client";
import { Download } from "lucide-react";
import { getServiceTips } from "../../lib/constants/serviceTips";

/**
 * Download Checklist button — generates a printable PDF checklist for a service.
 * Uses browser print dialog (no external PDF library required).
 */
export default function DownloadChecklist({ service, docs, elig, processingTime, fees, whereToApply }) {
  function handleDownload() {
    const tips = getServiceTips(service?.id);

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${service?.name} — Application Checklist</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #1a2733; padding: 32px; max-width: 680px; margin: auto; }
    .header { border-bottom: 3px solid #1a3a5c; padding-bottom: 12px; margin-bottom: 18px; }
    .brand { font-size: 11px; font-weight: bold; color: #1a3a5c; letter-spacing: 1px; text-transform: uppercase; }
    h1 { font-size: 20px; color: #1a3a5c; margin: 6px 0 2px; }
    .subtitle { font-size: 11px; color: #666; }
    .section { margin-bottom: 16px; }
    .section-title { background: #1a3a5c; color: white; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; padding: 5px 10px; border-radius: 4px 4px 0 0; }
    .section-body { border: 1px solid #ddd; border-top: none; border-radius: 0 0 4px 4px; padding: 10px 12px; }
    .item { display: flex; align-items: flex-start; gap: 8px; padding: 4px 0; border-bottom: 1px solid #f0f0f0; }
    .item:last-child { border-bottom: none; }
    .check { color: #2d7a4f; font-weight: bold; font-size: 13px; flex-shrink: 0; margin-top: 0px; }
    .tip-check { color: #e07b00; font-weight: bold; font-size: 13px; flex-shrink: 0; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
    .meta-item { background: #f8f9fa; border: 1px solid #e9ecef; border-radius: 4px; padding: 8px; }
    .meta-label { font-size: 9px; color: #999; text-transform: uppercase; font-weight: bold; }
    .meta-value { font-size: 11px; color: #1a3a5c; font-weight: bold; margin-top: 2px; }
    .disclaimer { margin-top: 20px; padding: 10px; background: #fff9e6; border: 1px solid #f5d8a0; border-radius: 4px; font-size: 10px; color: #7a4a00; }
    .footer { margin-top: 16px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">SevaSetu Telangana</div>
    <h1>${service?.name || "Application"} Checklist</h1>
    <div class="subtitle">AI-Powered Government Service Navigator · Generated ${new Date().toLocaleDateString("en-IN")}</div>
  </div>

  <div class="section">
    <div class="section-title">Required Documents</div>
    <div class="section-body">
      ${(docs || []).length > 0 ? (docs || []).map(doc => `<div class="item"><span class="check">☐</span><span>${doc}</span></div>`).join("") : "<p style='color:#999;font-size:11px'>See official portal for document requirements.</p>"}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Service Details</div>
    <div class="section-body">
      <div class="meta-grid">
        <div class="meta-item"><div class="meta-label">Processing Time</div><div class="meta-value">${processingTime || "See portal"}</div></div>
        <div class="meta-item"><div class="meta-label">Application Fee</div><div class="meta-value">${fees || "See portal"}</div></div>
        <div class="meta-item"><div class="meta-label">Where to Apply</div><div class="meta-value">${whereToApply || "See portal"}</div></div>
        <div class="meta-item"><div class="meta-label">Official Portal</div><div class="meta-value" style="word-break:break-all;font-size:10px">${service?.officialLink || "See portal"}</div></div>
      </div>
    </div>
  </div>

  ${elig && elig.length > 0 ? `<div class="section">
    <div class="section-title">Eligibility</div>
    <div class="section-body">
      ${elig.map(e => `<div class="item"><span class="check">✓</span><span>${e}</span></div>`).join("")}
    </div>
  </div>` : ""}

  <div class="section">
    <div class="section-title">Application Tips</div>
    <div class="section-body">
      ${tips.map(tip => `<div class="item"><span class="tip-check">★</span><span>${tip}</span></div>`).join("")}
    </div>
  </div>

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This checklist is for guidance purposes only. Always verify the final requirements on the official government portal before applying. SevaSetu is not affiliated with any government department.
  </div>

  <div class="footer">Generated by SevaSetu AI · sevasetu.telangana · For guidance only</div>
</body>
</html>`;

    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  }

  return (
    <button
      onClick={handleDownload}
      className="w-full inline-flex items-center justify-center gap-2 border border-[#1a3a5c] text-[#1a3a5c] hover:bg-[#1a3a5c] hover:text-white text-xs font-bold px-4 py-2.5 rounded transition-colors"
      aria-label={`Download ${service?.name} application checklist`}
    >
      <Download size={13} /> Download Checklist
    </button>
  );
}
