"use client";

import { useState } from "react";
import { Check, ClipboardCopy, ExternalLink, FileText } from "lucide-react";
import DraftSection from "./DraftSection";

/**
 * DraftPreview — full draft preview with editable fields, copy buttons,
 * and government-style cards.
 *
 * Props:
 *   draft — output of generateDraft() from lib/ocr/fieldMapper.js
 *   {
 *     serviceName, officialPortal, steps[], completionPercentage, readyToSubmit
 *   }
 *   steps[]: { stepName, fields[]: { label, value, filled, required } }
 */
export default function DraftPreview({ draft }) {
  const [copiedAll, setCopiedAll] = useState(false);
  const [localDraft, setLocalDraft] = useState(draft);

  if (!localDraft || !localDraft.steps || localDraft.steps.length === 0) {
    return (
      <div className="bg-white border border-gray-200 rounded-xl p-8 text-center shadow-sm">
        <FileText size={36} className="mx-auto text-gray-200 mb-3" />
        <p className="text-sm text-gray-400">
          Your generated application draft will appear here.
        </p>
        <p className="text-xs text-gray-300 mt-1">
          Select a service, upload documents, and click Generate.
        </p>
      </div>
    );
  }

  function handleFieldChange(stepIndex, fieldIndex, newValue) {
    setLocalDraft((prev) => {
      const updated = { ...prev, steps: [...prev.steps] };
      updated.steps[stepIndex] = {
        ...updated.steps[stepIndex],
        fields: [...updated.steps[stepIndex].fields],
      };
      updated.steps[stepIndex].fields[fieldIndex] = {
        ...updated.steps[stepIndex].fields[fieldIndex],
        value: newValue,
        filled: !!newValue,
      };
      return updated;
    });
  }

  function copyEntireDraft() {
    const lines = [];
    lines.push(`APPLICATION DRAFT — ${localDraft.serviceName}`);
    lines.push(`Official Portal: ${localDraft.officialPortal}`);
    lines.push("═".repeat(50));
    lines.push("");

    for (const step of localDraft.steps) {
      lines.push(`── ${step.stepName} ──`);
      for (const field of step.fields) {
        const val = field.value && field.value !== "—" ? field.value : "[NOT FILLED]";
        lines.push(`${field.label}: ${val}`);
      }
      lines.push("");
    }

    lines.push("═".repeat(50));
    lines.push("Generated by SevaSetu AI Draft Generator");
    lines.push("Disclaimer: Verify all details before submitting on official portal.");

    navigator.clipboard.writeText(lines.join("\n"));
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  }

  const { serviceName, officialPortal, completionPercentage, readyToSubmit } = localDraft;

  return (
    <div className="space-y-4">

      {/* ── Header card ── */}
      <div className="bg-white border border-gray-200 rounded-xl p-4 shadow-sm">
        <div className="flex items-start justify-between gap-3">
          <div>
            <h3 className="text-sm font-bold text-[#163A63] flex items-center gap-2">
              <FileText size={15} />
              {serviceName}
            </h3>
            <a
              href={officialPortal}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[11px] text-blue-500 hover:text-blue-700 flex items-center gap-0.5 mt-0.5"
            >
              {officialPortal} <ExternalLink size={9} />
            </a>
          </div>

          {/* Completion badge */}
          <div className={`text-xs font-bold px-2.5 py-1 rounded-full ${
            readyToSubmit
              ? "bg-green-100 text-green-700 border border-green-200"
              : "bg-orange-100 text-orange-700 border border-orange-200"
          }`}>
            {completionPercentage}% complete
          </div>
        </div>

        {/* Progress bar */}
        <div className="mt-3 h-1.5 bg-gray-100 rounded-full overflow-hidden">
          <div
            className={`h-full rounded-full transition-all duration-500 ${
              readyToSubmit ? "bg-green-500" : "bg-[#C89A2B]"
            }`}
            style={{ width: `${completionPercentage}%` }}
          />
        </div>

        {/* Copy entire draft */}
        <div className="mt-3 flex items-center justify-between">
          <p className="text-[10px] text-gray-400">
            {readyToSubmit
              ? "All required fields filled. Ready to copy."
              : "Fill missing required fields to complete the draft."}
          </p>
          <button
            onClick={copyEntireDraft}
            className="flex items-center gap-1.5 text-xs font-semibold text-[#163A63] hover:text-[#C89A2B] transition-colors px-2 py-1 rounded hover:bg-gray-50"
          >
            {copiedAll ? (
              <>
                <Check size={12} className="text-green-600" /> Copied!
              </>
            ) : (
              <>
                <ClipboardCopy size={12} /> Copy Entire Draft
              </>
            )}
          </button>
        </div>
      </div>

      {/* ── Step sections ── */}
      {localDraft.steps.map((step, stepIndex) => (
        <DraftSection
          key={stepIndex}
          stepName={step.stepName}
          stepIndex={stepIndex}
          fields={step.fields}
          onFieldChange={(fieldIndex, newValue) => handleFieldChange(stepIndex, fieldIndex, newValue)}
        />
      ))}

      {/* ── Disclaimer ── */}
      <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-3 text-[11px] text-yellow-800 leading-relaxed">
        <strong>Important:</strong> This is a preparation draft only. You must enter these details on the official
        government portal ({officialPortal}) to submit your actual application. SevaSetu does not submit applications
        on your behalf.
      </div>
    </div>
  );
}
