export const telanganaServices = [
  {
    id: "income-certificate",
    name: "Income Certificate",
    department: "Revenue Department, Telangana",
    category: "Certificate",
    applyAt: "MeeSeva / Telangana State Portal",
    processingTime: "7–15 working days",
    officialLink: "https://tg.meeseva.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Certifies annual family/individual income for scholarships, schemes and reservations.",
    overview:
      "An Income Certificate is issued by the Revenue Department of Telangana certifying the annual income of a family or individual. It is required for government schemes, educational scholarships, and reservation benefits.",
    documents: [
      "Application form",
      "Aadhaar card (applicant and family members)",
      "Address proof (Electricity bill / Voter ID / Ration Card)",
      "Income proof or salary certificate",
      "Passport-size photograph",
      "Mobile number linked to Aadhaar",
    ],
    eligibility: [
      "Applicant should be a resident of Telangana",
      "Applicant should provide valid income-related documents",
      "Valid Aadhaar card required",
    ],
    steps: [
      "Keep all required documents ready (originals + photocopies)",
      "Visit nearest MeeSeva centre or go to tg.meeseva.gov.in",
      "Select Revenue Department → Income Certificate",
      "Fill in applicant details and annual family income",
      "Upload scanned copies of all required documents",
      "Pay applicable service fee (approx. ₹35)",
      "Note the Application Reference Number",
      "Track application status online or at MeeSeva",
      "Download or collect certificate after approval (7–15 working days)",
    ],
    fees: "Approximately ₹35 (service charge at MeeSeva centre)",
    mistakes: [
      "Incorrect or mismatched income proof",
      "Address on Aadhaar not matching application",
      "Missing passport-size photograph or signature",
      "Uploading blurry or incomplete document scans",
      "Using unofficial agents or third-party websites",
    ],
  },
  {
    id: "caste-certificate",
    name: "Caste Certificate",
    department: "Revenue Department, Telangana",
    category: "Certificate",
    applyAt: "MeeSeva / Revenue Department / Tahsildar Office",
    processingTime: "15–30 working days",
    officialLink: "https://tg.meeseva.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Certifies caste/community for SC, ST, BC, OBC reservation benefits in education and employment.",
    overview:
      "A Caste Certificate is issued by the Revenue Department to certify the caste/community of an individual for availing reservations in education, employment, and government schemes under SC, ST, OBC, or BC categories as per Telangana government schedule.",
    documents: [
      "Application form",
      "Aadhaar card (applicant)",
      "Address proof (Electricity bill / Voter ID)",
      "Community or caste proof if available",
      "Parent's or ancestor's caste certificate if available",
      "School Transfer Certificate or SSC Certificate",
      "Ration Card",
      "Passport-size photograph",
    ],
    eligibility: [
      "Applicant should belong to an eligible caste/community category as per Telangana government schedule",
      "Applicant should be a resident of Telangana",
      "Valid domicile proof in Telangana required",
    ],
    steps: [
      "Keep all required documents ready (originals + photocopies)",
      "Visit nearest MeeSeva centre or Tahsildar office",
      "Select Revenue Department → Caste Certificate",
      "Fill in personal and family/community details",
      "Upload all required documents",
      "Pay applicable service fee (approx. ₹35–₹45)",
      "Application is forwarded to Tahsildar for field verification",
      "Tahsildar may conduct local enquiry to verify community claim",
      "Certificate issued after verification (15–30 working days)",
    ],
    fees: "Approximately ₹35–₹45 (service charge at MeeSeva centre)",
    mistakes: [
      "Not providing ancestral caste proof or parent's certificate",
      "Name mismatch across different documents",
      "Applying in wrong caste category",
      "Missing school records or Transfer Certificate",
      "Approaching unofficial agents instead of MeeSeva or Tahsildar",
    ],
  },
  {
    id: "residence-certificate",
    name: "Residence Certificate",
    department: "Revenue Department, Telangana",
    category: "Certificate",
    applyAt: "MeeSeva / Revenue Department / Tahsildar Office",
    processingTime: "7–10 working days",
    officialLink: "https://tg.meeseva.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Confirms permanent residence in Telangana for admissions, employment and government benefits.",
    overview:
      "A Residence Certificate (also called Domicile Certificate) confirms that the applicant is a permanent resident of a specific location in Telangana. It is required for educational admissions, employment applications, and to avail government scheme benefits reserved for Telangana residents.",
    documents: [
      "Application form",
      "Aadhaar card",
      "Address proof (Electricity bill / Water bill / Telephone bill)",
      "Voter ID Card",
      "Ration Card (if available)",
      "Property Tax receipt (if applicable)",
      "Passport-size photograph",
    ],
    eligibility: [
      "Applicant should be residing in Telangana",
      "Applicant should provide valid address proof in Telangana",
      "Valid Aadhaar card with current Telangana address",
    ],
    steps: [
      "Keep all required documents ready (originals + photocopies)",
      "Visit nearest MeeSeva centre or Tahsildar office",
      "Select Revenue Department → Residence / Domicile Certificate",
      "Enter personal and address details",
      "Upload required documents",
      "Pay applicable service fee (approx. ₹35)",
      "Tahsildar verifies residence through records or field visit",
      "Certificate issued within 7–10 working days",
    ],
    fees: "Approximately ₹35 (service charge at MeeSeva centre)",
    mistakes: [
      "Address on Aadhaar not matching the application address",
      "Missing utility bill as address proof",
      "Applying from a rented address without proper tenancy proof",
      "Incomplete form submission",
      "Not carrying original documents for verification",
    ],
  },
  {
    id: "birth-certificate",
    name: "Birth Certificate",
    department: "Municipal Administration / GHMC / Gram Panchayat",
    category: "Certificate",
    applyAt: "GHMC / Municipality / Gram Panchayat / MeeSeva",
    processingTime: "3–7 working days (if birth already registered)",
    officialLink: "https://www.ghmc.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Primary identity document recording birth, required for school admission, Aadhaar and passport.",
    overview:
      "A Birth Certificate is issued by the municipal authority or gram panchayat to record the birth of a child. It is a primary identity document required for school admission, Aadhaar enrollment, passport application, and many other government services. Registration should ideally be done within 21 days of birth.",
    documents: [
      "Hospital discharge summary / Certificate of birth from hospital",
      "Parent's Aadhaar cards (both)",
      "Parent's marriage certificate",
      "Address proof of parents",
      "Application form",
      "Ration Card (if available)",
    ],
    eligibility: [
      "Birth should have occurred in Telangana",
      "Parent or legal guardian can apply with valid supporting documents",
      "Registration within 21 days of birth is free; late fees apply after that",
      "Delayed registration (after 1 year) requires Judicial Magistrate order",
    ],
    steps: [
      "Contact GHMC / Municipal Office / Gram Panchayat with jurisdiction over the birth location",
      "Obtain birth registration form",
      "Submit hospital birth record and parents' documents",
      "Fill prescribed birth registration form",
      "Pay applicable fee (free within 21 days; late fee applies after)",
      "Receive acknowledgment slip with reference number",
      "Collect birth certificate within 3–7 working days",
      "For births in private hospitals: confirm hospital has submitted birth notification to municipality",
    ],
    fees: "Free if registered within 21 days of birth. Late registration fees apply thereafter.",
    mistakes: [
      "Delaying registration beyond 21 days of birth",
      "Not collecting birth intimation/record from hospital before discharge",
      "Name mismatch in parents' documents",
      "Approaching agents instead of visiting GHMC / municipal office directly",
      "Not verifying that the hospital submitted the birth notification",
    ],
  },
  { id: "death-certificate",    name: "Death Certificate",          department: "Municipal Administration / GHMC", category: "Certificate", applyAt: "GHMC / Municipality / MeeSeva", processingTime: "3–7 working days", officialLink: "https://cdma.telangana.gov.in", lastVerified: "2026-07-01", status: "coming-soon", shortDesc: "Official record of death for legal, property and insurance purposes.", overview: "", documents: [], eligibility: [], steps: [], fees: "", mistakes: [] },
  { id: "ration-card",          name: "Ration Card",                department: "Civil Supplies Department, Telangana", category: "Scheme", applyAt: "Civil Supplies / MeeSeva", processingTime: "30–45 days", officialLink: "https://tgfood.gov.in", lastVerified: "2026-07-01", status: "coming-soon", shortDesc: "Provides access to subsidised food grains under Public Distribution System.", overview: "", documents: [], eligibility: [], steps: [], fees: "", mistakes: [] },
  { id: "aadhaar-update",       name: "Aadhaar Update",             department: "UIDAI", category: "Identity", applyAt: "Aadhaar Seva Kendra / UIDAI Portal", processingTime: "7–10 working days", officialLink: "https://uidai.gov.in", lastVerified: "2026-07-01", status: "coming-soon", shortDesc: "Update demographic or biometric information in Aadhaar through UIDAI channels.", overview: "", documents: [], eligibility: [], steps: [], fees: "", mistakes: [] },
  { id: "driving-licence",      name: "Driving Licence",            department: "Transport Department, Telangana", category: "Transport", applyAt: "RTO / Sarathi Portal", processingTime: "15–30 days", officialLink: "https://sarathi.parivahan.gov.in", lastVerified: "2026-07-01", status: "coming-soon", shortDesc: "Apply for fresh driving licence or renewal through Telangana RTO.", overview: "", documents: [], eligibility: [], steps: [], fees: "", mistakes: [] },
  { id: "voter-id",             name: "Voter ID",                   department: "Election Commission of India", category: "Identity", applyAt: "Electoral Registration Officer / Voter Helpline", processingTime: "15–30 days", officialLink: "https://voterportal.eci.gov.in", lastVerified: "2026-07-01", status: "coming-soon", shortDesc: "Enrol as a voter or update Voter ID details through the Election Commission.", overview: "", documents: [], eligibility: [], steps: [], fees: "", mistakes: [] },
  { id: "ts-schemes",           name: "Telangana Govt. Schemes",    department: "Various Departments, Govt. of Telangana", category: "Scheme", applyAt: "Respective Dept. Portal / MeeSeva", processingTime: "Varies by scheme", officialLink: "https://telangana.gov.in", lastVerified: "2026-07-01", status: "coming-soon", shortDesc: "Overview of flagship welfare and development schemes by the Telangana government.", overview: "", documents: [], eligibility: [], steps: [], fees: "", mistakes: [] },
];

export function getServiceById(id) {
  return telanganaServices.find((s) => s.id === id) || null;
}

export const activeServices = telanganaServices.filter((s) => s.status === "active");
export const comingSoonServices = telanganaServices.filter((s) => s.status === "coming-soon");
