export const telanganaServices = [
  {
    id: "passport",
    name: "Passport",
    department: "Ministry of External Affairs / Passport Seva",
    category: "Identity & Travel",
    applyAt: "Passport Seva Portal / PSK / POPSK",
    processingTime: "Depends on application type and police verification",
    officialLink: "https://www.passportindia.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    hasDraftGenerator: true,
    shortDesc: "Apply for fresh passport, renewal, Tatkaal, minor passport, corrections, appointment guidance and police verification support.",
    overview: "A passport is an official travel document issued by the Government of India through the Ministry of External Affairs. It certifies identity and nationality for international travel and is widely accepted as photo identity proof.",
    documents: ["Proof of Date of Birth (Birth certificate / 10th marksheet)", "Proof of Address (Aadhaar / Voter ID / Electricity bill)", "Proof of Identity (Aadhaar / PAN / Voter ID)", "Passport-size photographs (white background)", "Old passport (for reissue)"],
    eligibility: ["Any Indian citizen can apply", "No age restriction — even newborns eligible", "Minors require parental consent"],
    steps: ["Register on passportindia.gov.in", "Fill application form", "Upload documents and pay fee", "Book appointment at PSK/POPSK", "Visit PSK on appointment date with originals", "Police verification", "Passport dispatched via Speed Post"],
    fees: "Normal 36 pages: ₹1500. Tatkaal: ₹3500. Minor: ₹1000.",
    mistakes: ["Document name mismatch", "Address proof older than 3 months", "Not carrying originals to PSK", "Booking wrong PSK"],
  },
  {
    id: "income-certificate",
    name: "Income Certificate",
    department: "Revenue Department, Telangana",
    category: "Certificate",
    applyAt: "MeeSeva / meeseva.telangana.gov.in",
    processingTime: "7–15 working days",
    officialLink: "https://meeseva.telangana.gov.in/",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Certifies annual family/individual income for scholarships, schemes, reservations and government benefits.",
    overview: "An Income Certificate is issued by the Revenue Department of Telangana certifying the annual income of a family or individual. Required for scholarships, fee reimbursement, welfare schemes, and reservation benefits.",
    documents: ["Application form", "Aadhaar card", "Address proof", "Income proof or salary certificate", "Passport-size photo", "Mobile linked to Aadhaar"],
    eligibility: ["Resident of Telangana", "Valid Aadhaar card", "Verifiable income documentation"],
    steps: ["Visit MeeSeva or meeseva.telangana.gov.in", "Select Revenue → Income Certificate", "Fill details and upload documents", "Pay ₹35 fee", "Tahsildar verification", "Certificate issued in 7–15 days"],
    fees: "Approximately ₹35 at MeeSeva",
    mistakes: ["Income mismatch", "Aadhaar address not matching", "Missing photograph", "Using unofficial agents"],
  },
  {
    id: "caste-certificate",
    name: "Caste Certificate",
    department: "Revenue Department, Telangana",
    category: "Certificate",
    applyAt: "MeeSeva / Tahsildar Office",
    processingTime: "15–30 working days",
    officialLink: "https://meeseva.telangana.gov.in/",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Certifies SC/ST/BC/OBC community for reservation benefits in education, employment and government schemes.",
    overview: "A Caste Certificate certifies a person's caste or community as per the Telangana government schedule for availing reservations in education, employment, and government schemes.",
    documents: ["Application form", "Aadhaar card", "Address proof", "School TC or SSC certificate", "Parent's caste certificate", "Ration Card", "Photograph"],
    eligibility: ["Belong to recognized SC/ST/BC/OBC community", "Resident of Telangana", "Documentary proof of community"],
    steps: ["Visit MeeSeva or Tahsildar office", "Select Revenue → Caste Certificate", "Fill community details", "Upload documents", "Pay ₹35–₹45", "Tahsildar field verification", "Certificate in 15–30 days"],
    fees: "Approximately ₹35–₹45",
    mistakes: ["Not providing parent's caste certificate", "Name mismatch", "Wrong caste category", "Missing school records"],
  },
  {
    id: "residence-certificate",
    name: "Residence Certificate",
    department: "Revenue Department, Telangana",
    category: "Certificate",
    applyAt: "MeeSeva / Tahsildar Office",
    processingTime: "7–10 working days",
    officialLink: "https://meeseva.telangana.gov.in/",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Confirms permanent residence in Telangana for admissions, employment and government benefits.",
    overview: "A Residence Certificate confirms permanent residency in Telangana. Required for educational admissions, government jobs with domicile reservation, and state welfare schemes.",
    documents: ["Application form", "Aadhaar card", "Address proof (utility bill within 1 year)", "Voter ID", "Ration Card", "Photograph"],
    eligibility: ["Residing in Telangana", "Valid address proof", "Aadhaar with current address"],
    steps: ["Visit MeeSeva or Tahsildar office", "Select Revenue → Residence Certificate", "Fill address details", "Upload documents", "Pay ₹35", "Tahsildar verifies", "Certificate in 7–10 days"],
    fees: "Approximately ₹35",
    mistakes: ["Aadhaar address mismatch", "Utility bill older than 1 year", "No tenancy proof for rented address"],
  },
  {
    id: "birth-certificate",
    name: "Birth Certificate",
    department: "Municipal Administration / GHMC / Gram Panchayat",
    category: "Certificate",
    applyAt: "GHMC / Municipality / Gram Panchayat / MeeSeva",
    processingTime: "3–7 working days (if registered within 21 days)",
    officialLink: "https://www.ghmc.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Primary identity document recording birth, required for school admission, Aadhaar and passport.",
    overview: "A Birth Certificate is the official government record of a child's birth. It is the foundational identity document required for school admission, Aadhaar, passport, and many other services.",
    documents: ["Hospital birth record", "Parents' Aadhaar cards", "Parents' marriage certificate", "Address proof", "Application form"],
    eligibility: ["Birth occurred in Telangana", "Parent or guardian can apply", "Free within 21 days of birth"],
    steps: ["Get hospital birth record before discharge", "Contact GHMC/Municipality/Gram Panchayat", "Fill registration form", "Submit documents", "Pay fee (free within 21 days)", "Collect certificate in 3–7 days"],
    fees: "Free within 21 days. Late fee applies after.",
    mistakes: ["Delaying beyond 21 days", "Not collecting hospital birth record", "Name mismatch in parents' docs"],
  },
  {
    id: "death-certificate",
    name: "Death Certificate",
    department: "Municipal Administration / GHMC / Gram Panchayat",
    category: "Certificate",
    applyAt: "GHMC / Municipality / Gram Panchayat / MeeSeva",
    processingTime: "3–7 working days",
    officialLink: "https://cdma.telangana.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Official record of death for legal, property, insurance and succession purposes.",
    overview: "A Death Certificate is issued by the municipal authority to officially record a person's death. Required for property transfer, insurance claims, pension settlement, and legal succession.",
    documents: ["Hospital death certificate / doctor's certificate", "Deceased's Aadhaar card", "Applicant's Aadhaar card", "Address proof", "Application form"],
    eligibility: ["Death occurred in Telangana", "Family member or authorized person can apply", "Registration should be within 21 days"],
    steps: ["Obtain death certificate from hospital", "Visit GHMC/Municipality/Gram Panchayat", "Fill death registration form", "Submit hospital certificate and documents", "Collect death certificate in 3–7 days"],
    fees: "Free within 21 days. Late fee applies after.",
    mistakes: ["Delaying registration", "Not obtaining hospital death certificate", "Incorrect deceased details"],
  },
  {
    id: "ration-card",
    name: "Ration Card",
    department: "Civil Supplies Department, Telangana",
    category: "Scheme",
    applyAt: "Civil Supplies Office / MeeSeva",
    processingTime: "30–45 days",
    officialLink: "https://tgfood.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Provides access to subsidised food grains under Public Distribution System.",
    overview: "A Ration Card entitles a household to purchase subsidised food grains from Fair Price Shops under PDS. Also serves as address and identity proof.",
    documents: ["Application form", "Aadhaar cards of all family members", "Address proof", "Income certificate (for BPL)", "Photographs of all members"],
    eligibility: ["Resident of Telangana", "No ration card in another state", "Income criteria for category"],
    steps: ["Visit Civil Supplies office or MeeSeva", "Submit application with family Aadhaar details", "Field verification", "Card issued after approval in 30–45 days"],
    fees: "₹10–₹35 at MeeSeva",
    mistakes: ["Not enrolling all family members", "Duplicate card in another state", "Wrong income category"],
  },
  {
    id: "aadhaar-update",
    name: "Aadhaar Update",
    department: "UIDAI",
    category: "Identity",
    applyAt: "myaadhaar.uidai.gov.in / Aadhaar Seva Kendra",
    processingTime: "7–10 working days",
    officialLink: "https://myaadhaar.uidai.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Update demographic or biometric information in Aadhaar through official UIDAI channels.",
    overview: "Aadhaar Update allows holders to correct or update name, address, DOB, mobile, email, or biometric data through UIDAI official channels.",
    documents: ["Existing Aadhaar card", "Supporting document for the field being updated", "Mobile number linked to Aadhaar (for online)"],
    eligibility: ["Must hold valid Aadhaar", "Mobile linked for online updates", "Visit centre for biometric updates"],
    steps: ["Visit myaadhaar.uidai.gov.in or Aadhaar Seva Kendra", "Select update type", "Upload supporting document", "Pay ₹50 (centre) or free (online address)", "Track using URN"],
    fees: "Online address: Free. Centre updates: ₹50. Biometric: ₹100.",
    mistakes: ["Using unofficial websites", "Document mismatch", "Not booking appointment"],
  },
  {
    id: "driving-licence",
    name: "Driving Licence",
    department: "Transport Department, Telangana",
    category: "Transport",
    applyAt: "sarathi.parivahan.gov.in / RTO",
    processingTime: "15–30 days after passing test",
    officialLink: "https://sarathi.parivahan.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    hasDraftGenerator: true,
    shortDesc: "Apply for Learner Licence, permanent DL, renewal, or duplicate through Telangana RTO.",
    overview: "A Driving Licence authorises a person to drive motor vehicles on public roads. Apply for LL first, wait 30 days, then apply for permanent DL after passing driving test.",
    documents: ["Aadhaar card", "Passport-size photographs", "Form 4", "Learner Licence (for DL)", "Medical certificate Form 1A (commercial)"],
    eligibility: ["18+ for cars/motorcycles", "16+ for gearless 50cc", "Must pass LL test first"],
    steps: ["Apply for Learner Licence on Sarathi portal", "Pass LL test at RTO", "Wait 30 days", "Apply for permanent DL", "Pass driving test", "DL dispatched in 15–30 days"],
    fees: "LL: ₹200. DL: ₹200. Renewal: ₹200.",
    mistakes: ["Applying for DL before 30 days", "Not carrying originals", "Wrong vehicle class", "Uninsured test vehicle"],
  },
  {
    id: "voter-id",
    name: "Voter ID",
    department: "Election Commission of India",
    category: "Identity",
    applyAt: "voters.eci.gov.in / ERO Office",
    processingTime: "15–30 days",
    officialLink: "https://voters.eci.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Electoral Photo Identity Card for voting and widely accepted as identity proof.",
    overview: "Voter ID (EPIC) is issued by the Election Commission as proof of voter registration. Required for voting and widely used as photo identity and address proof.",
    documents: ["Form 6", "Age proof (Aadhaar/birth certificate)", "Address proof", "Passport-size photograph"],
    eligibility: ["Indian citizen aged 18+", "Ordinary resident of the constituency"],
    steps: ["Visit voters.eci.gov.in", "Fill Form 6", "Upload documents", "BLO verification", "Card dispatched by post"],
    fees: "Free — no charges",
    mistakes: ["Wrong constituency", "Not updating after moving", "Missing BLO verification"],
  },
  {
    id: "pan-card",
    name: "PAN Card",
    department: "Income Tax Department, Government of India",
    category: "Finance",
    applyAt: "onlineservices.nsdl.com / utiitsl.com / incometax.gov.in",
    processingTime: "15–20 days (physical) / Instant (e-PAN)",
    officialLink: "https://www.onlineservices.nsdl.com",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Permanent Account Number for tax filing, banking, and financial transactions.",
    overview: "PAN is a 10-digit code issued by the Income Tax Department. Mandatory for tax returns, financial transactions above ₹50,000, bank accounts, and widely used as identity proof.",
    documents: ["Proof of Identity (Aadhaar/Voter ID/Passport)", "Proof of Address", "Proof of Date of Birth", "Photographs", "Form 49A"],
    eligibility: ["Any Indian citizen", "No age limit — minors can apply", "Entities (companies, firms) also eligible"],
    steps: ["Visit onlineservices.nsdl.com or incometax.gov.in", "Fill Form 49A", "Upload documents and photo", "Pay ₹107", "PAN generated in 7–10 days", "Card delivered in 15–20 days"],
    fees: "Physical: ₹107. Instant e-PAN via Aadhaar: Free.",
    mistakes: ["Applying for duplicate PAN (illegal)", "Name mismatch", "Not linking with Aadhaar"],
  },
  {
    id: "telangana-schemes",
    name: "Telangana Govt. Schemes",
    department: "Various Departments, Govt. of Telangana",
    category: "Scheme",
    applyAt: "Respective Department Portal / MeeSeva",
    processingTime: "Varies by scheme",
    officialLink: "https://telangana.gov.in",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Overview of welfare and development schemes by the Telangana government.",
    overview: "Telangana offers multiple welfare schemes covering agriculture, education, healthcare, housing, and social security. Apply through respective department portals or MeeSeva centres.",
    documents: ["Varies by scheme — typically Aadhaar, income certificate, caste certificate"],
    eligibility: ["Varies by scheme — check specific scheme requirements"],
    steps: ["Identify the relevant scheme", "Check eligibility criteria", "Visit MeeSeva or department portal", "Submit application with documents", "Track application status"],
    fees: "Varies by scheme",
    mistakes: ["Applying to wrong scheme", "Incomplete documentation", "Missing eligibility criteria"],
  },
  {
    id: "meeseva-services",
    name: "MeeSeva Services",
    department: "Government of Telangana",
    category: "Platform",
    applyAt: "Any MeeSeva Centre / meeseva.telangana.gov.in",
    processingTime: "Varies by service (3–45 days)",
    officialLink: "https://meeseva.telangana.gov.in/",
    lastVerified: "2026-07-01",
    status: "active",
    shortDesc: "Telangana's citizen service platform with 600+ services through 3500+ centres.",
    overview: "MeeSeva is the Government of Telangana's official citizen service delivery platform providing 600+ government services through over 3500 centres across the state.",
    documents: ["Varies by service — carry Aadhaar, originals, and photocopies"],
    eligibility: ["Any Telangana citizen can use MeeSeva services"],
    steps: ["Visit nearest MeeSeva centre or meeseva.telangana.gov.in", "Select the required service", "Submit documents and pay fee", "Collect acknowledgement receipt", "Track status using reference number"],
    fees: "₹10–₹50 per service (varies)",
    mistakes: ["Not carrying originals", "Visiting on government holidays", "Not collecting receipt"],
  },
];

export function getServiceById(id) {
  return telanganaServices.find((s) => s.id === id) || null;
}

export const activeServices = telanganaServices.filter((s) => s.status === "active");
