/**
 * Driving Licence Application Form Schema
 * Based on official Telangana Transport Department form (Form 2 / Form 4)
 * Covers Learner Licence + Permanent Licence application
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const drivingLicenceSchema = {
  serviceName: "Driving Licence (Learner / Permanent)",
  officialPortal: "https://sarathi.parivahan.gov.in",
  disclaimer:
    "This is a draft generated by SevaSetu for reference purposes only. Final submission must be completed through the official Telangana Transport Department portal (Sarathi Parivahan).",
  formReference: "Form 2 (Learner Licence) / Form 4 (Permanent Licence) — Telangana Transport Department",

  steps: [
    {
      id: "application-type",
      title: "Application Type",
      description: "Select type of licence you are applying for",
      fields: [
        { id: "applicationType", label: "Application Type", type: "radio", required: true, ocrSupported: false, options: ["Learner Licence (Fresh)", "Learner Licence (Additional Class)", "Permanent Licence (Fresh)", "Permanent Licence (Renewal)", "Duplicate Licence", "International Driving Permit"] },
        { id: "rtoOffice", label: "RTO / Licensing Authority", type: "text", required: true, ocrSupported: false, placeholder: "e.g. RTA Hyderabad Central" },
      ],
    },
    {
      id: "personal-details",
      title: "Personal Details",
      description: "Applicant personal information (Form 1 fields)",
      fields: [
        { id: "fullName", label: "Full Name (as on Aadhaar)", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar" },
        { id: "fatherHusbandName", label: "Father's / Husband's Name", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar/PAN" },
        { id: "motherName", label: "Mother's Name", type: "text", required: false, ocrSupported: false },
        { id: "dateOfBirth", label: "Date of Birth", type: "date", required: true, ocrSupported: true, sourceHint: "Aadhaar/SSC" },
        { id: "age", label: "Age (as on date)", type: "text", required: false, ocrSupported: false },
        { id: "gender", label: "Gender", type: "radio", required: true, ocrSupported: true, options: ["Male", "Female", "Transgender"] },
        { id: "nationality", label: "Nationality", type: "text", required: true, ocrSupported: false, placeholder: "Indian" },
        { id: "bloodGroup", label: "Blood Group", type: "select", required: true, ocrSupported: false, options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "Unknown"] },
        { id: "qualification", label: "Educational Qualification", type: "select", required: true, ocrSupported: false, options: ["Illiterate", "Below 8th", "8th Pass", "10th Pass", "12th Pass", "Graduate", "Post Graduate", "Professional Degree", "Others"] },
        { id: "mobileNumber", label: "Mobile Number", type: "text", required: true, ocrSupported: false, validation: "mobile" },
        { id: "emailId", label: "Email ID", type: "email", required: false, ocrSupported: false, validation: "email" },
        { id: "aadhaarNumber", label: "Aadhaar Number", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar", validation: "aadhaar" },
        { id: "panNumber", label: "PAN Number (if available)", type: "text", required: false, ocrSupported: true, sourceHint: "PAN", validation: "pan" },
        { id: "identificationMark1", label: "Identification Mark 1", type: "text", required: false, ocrSupported: false, placeholder: "e.g. Mole on left cheek" },
        { id: "identificationMark2", label: "Identification Mark 2", type: "text", required: false, ocrSupported: false },
        { id: "organDonor", label: "Willing to be Organ Donor?", type: "radio", required: false, ocrSupported: false, options: ["Yes", "No"] },
      ],
    },
    {
      id: "address-details",
      title: "Address Details",
      description: "Communication and permanent address",
      fields: [
        { id: "commHouseStreet", label: "House No. / Street / Locality", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar" },
        { id: "commCity", label: "City / Town / Village", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar" },
        { id: "commDistrict", label: "District", type: "district-select", required: true, ocrSupported: true, sourceHint: "Aadhaar" },
        { id: "commState", label: "State", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar" },
        { id: "commPinCode", label: "PIN Code", type: "text", required: true, ocrSupported: true, sourceHint: "Aadhaar", validation: "pincode" },
        { id: "permanentSameAsComm", label: "Permanent address same as communication?", type: "radio", required: true, ocrSupported: false, options: ["Yes", "No"] },
        { id: "permHouseStreet", label: "Permanent House No. / Street", type: "text", required: false, ocrSupported: false },
        { id: "permCity", label: "Permanent City / Town", type: "text", required: false, ocrSupported: false },
        { id: "permDistrict", label: "Permanent District", type: "text", required: false, ocrSupported: false },
        { id: "permState", label: "Permanent State", type: "text", required: false, ocrSupported: false },
        { id: "permPinCode", label: "Permanent PIN Code", type: "text", required: false, ocrSupported: false, validation: "pincode" },
      ],
    },
    {
      id: "vehicle-class",
      title: "Vehicle Class",
      description: "Category of vehicle(s) you want to drive",
      fields: [
        { id: "vehicleClass", label: "Vehicle Class(es) Applied For", type: "multi-select", required: true, ocrSupported: false, options: ["MC 50CC (Motorcycle ≤50cc)", "MCWOG (Motorcycle Without Gear)", "MCWG (Motorcycle With Gear)", "LMV-NT (Light Motor Vehicle Non-Transport / Car)", "LMV (Light Motor Vehicle)", "HMV (Heavy Motor Vehicle)", "HGMV (Heavy Goods Motor Vehicle)", "HPMV (Heavy Passenger Motor Vehicle)", "Trailer", "Others"] },
      ],
    },
    {
      id: "existing-licence",
      title: "Existing Licence Details",
      description: "Details of existing licence (for renewal / additional class)",
      fields: [
        { id: "hasExistingLicence", label: "Do you have an existing Driving Licence?", type: "radio", required: true, ocrSupported: false, options: ["Yes", "No"] },
        { id: "existingLicenceNumber", label: "Existing Licence Number", type: "text", required: false, ocrSupported: true, sourceHint: "Existing DL" },
        { id: "existingLicenceDateOfIssue", label: "Date of Issue", type: "date", required: false, ocrSupported: true },
        { id: "existingLicenceDateOfExpiry", label: "Date of Expiry", type: "date", required: false, ocrSupported: true },
        { id: "existingLicenceIssuingAuthority", label: "Issuing RTO", type: "text", required: false, ocrSupported: true },
        { id: "existingLicenceVehicleClasses", label: "Vehicle Classes on Existing Licence", type: "text", required: false, ocrSupported: true },
        { id: "learnerLicenceNumber", label: "Learner Licence Number (for DL application)", type: "text", required: false, ocrSupported: false },
        { id: "learnerLicenceDateOfIssue", label: "Learner Licence Date of Issue", type: "date", required: false, ocrSupported: false },
        { id: "learnerLicenceValidTill", label: "Learner Licence Valid Till", type: "date", required: false, ocrSupported: false },
      ],
    },
    {
      id: "medical-details",
      title: "Medical Details (Form 1A)",
      description: "Medical certificate and physical fitness declaration",
      fields: [
        { id: "medicalCertificateAvailable", label: "Do you have a Medical Certificate (Form 1A)?", type: "radio", required: true, ocrSupported: false, options: ["Yes", "No"] },
        { id: "medicalCertificateDate", label: "Medical Certificate Date", type: "date", required: false, ocrSupported: false },
        { id: "medicalCertificateDoctor", label: "Doctor Name / Registration No.", type: "text", required: false, ocrSupported: false },
        { id: "medicalCertificateHospital", label: "Hospital / Clinic Name", type: "text", required: false, ocrSupported: false },
        { id: "eyesightRight", label: "Right Eye Vision", type: "text", required: false, ocrSupported: false, placeholder: "e.g. 6/6" },
        { id: "eyesightLeft", label: "Left Eye Vision", type: "text", required: false, ocrSupported: false, placeholder: "e.g. 6/6" },
        { id: "wearsGlasses", label: "Do you wear corrective lenses?", type: "radio", required: false, ocrSupported: false, options: ["Yes", "No"] },
        { id: "colorBlind", label: "Color blindness?", type: "radio", required: false, ocrSupported: false, options: ["Yes", "No"] },
        { id: "physicalDisability", label: "Any physical disability?", type: "radio", required: false, ocrSupported: false, options: ["Yes", "No"] },
        { id: "physicalDisabilityDetails", label: "If yes, provide details", type: "text", required: false, ocrSupported: false },
        { id: "height", label: "Height (cm)", type: "text", required: false, ocrSupported: false },
        { id: "weight", label: "Weight (kg)", type: "text", required: false, ocrSupported: false },
        { id: "medicalFitDeclaration", label: "I declare that I am physically and mentally fit to drive", type: "checkbox", required: true, ocrSupported: false },
      ],
    },
    {
      id: "emergency-contact",
      title: "Emergency Contact",
      description: "Contact person in case of emergency",
      fields: [
        { id: "emergencyContactName", label: "Emergency Contact Name", type: "text", required: true, ocrSupported: false },
        { id: "emergencyContactRelation", label: "Relation", type: "text", required: false, ocrSupported: false, placeholder: "e.g. Father, Spouse" },
        { id: "emergencyContactMobile", label: "Emergency Contact Mobile", type: "text", required: true, ocrSupported: false, validation: "mobile" },
        { id: "emergencyContactAddress", label: "Emergency Contact Address", type: "text", required: false, ocrSupported: false },
      ],
    },
    {
      id: "declarations",
      title: "Applicant Declarations",
      description: "Mandatory declarations as per Form 1",
      fields: [
        { id: "declareNoPendingCases", label: "No pending criminal/civil cases related to motor vehicles", type: "checkbox", required: true, ocrSupported: false },
        { id: "declareNoPrevDisqualification", label: "Not previously disqualified from holding a licence", type: "checkbox", required: true, ocrSupported: false },
        { id: "declareNoSuspension", label: "Licence not suspended / revoked / cancelled", type: "checkbox", required: true, ocrSupported: false },
        { id: "declareNotRefused", label: "Licence application not previously refused", type: "checkbox", required: true, ocrSupported: false },
        { id: "declareNoEpilepsy", label: "Not suffering from epilepsy or sudden attacks of unconsciousness", type: "checkbox", required: true, ocrSupported: false },
        { id: "declareMentallyFit", label: "Mentally fit and not suffering from any mental disorder", type: "checkbox", required: true, ocrSupported: false },
        { id: "declareInfoCorrect", label: "I declare that the information provided is true and correct", type: "checkbox", required: true, ocrSupported: false },
        { id: "declarationPlace", label: "Place", type: "text", required: true, ocrSupported: false, placeholder: "City where signing" },
        { id: "declarationDate", label: "Date", type: "date", required: true, ocrSupported: false },
      ],
    },
    {
      id: "review-download",
      title: "Review & Download",
      description: "Review your complete draft and download PDF",
      fields: [],
    },
  ],
};
