/**
 * Learner Driving Licence Form Schema
 * ─────────────────────────────────────────────────────────────────────────────
 * Placeholder fields — will be updated after official form screenshots are provided.
 * Based on Form 2 (Application for Learner's Licence) from Sarathi portal.
 */

export const learnerLicenceSchema = {
  serviceName: "Learner Driving Licence",
  officialPortal: "https://sarathi.parivahan.gov.in",
  formReference: "Form 2 (Application for Learner's Licence)",

  steps: [
    "Personal Details",
    "Address Details",
    "Vehicle Class",
    "Document Upload",
    "Review & Generate",
  ],

  fields: [
    // ── Step 1: Personal Details ──────────────────────────────────────────
    {
      id: "applicant_name",
      label: "Applicant Full Name",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "Full name as on Aadhaar card",
      validation: { minLength: 2, maxLength: 100, pattern: "^[A-Za-z\\s]+$" },
      step: 0,
    },
    {
      id: "father_husband_name",
      label: "Father's / Husband's Name",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "Father's or husband's full name",
      validation: { minLength: 2, maxLength: 100 },
      step: 0,
    },
    {
      id: "date_of_birth",
      label: "Date of Birth",
      type: "date",
      required: true,
      ocrSupported: true,
      placeholder: "DD/MM/YYYY",
      validation: { format: "DD/MM/YYYY" },
      step: 0,
    },
    {
      id: "gender",
      label: "Gender",
      type: "select",
      required: true,
      ocrSupported: true,
      placeholder: "Select gender",
      validation: { options: ["Male", "Female", "Transgender"] },
      step: 0,
    },
    {
      id: "blood_group",
      label: "Blood Group",
      type: "select",
      required: false,
      ocrSupported: false,
      placeholder: "Select blood group",
      validation: { options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "Unknown"] },
      step: 0,
    },
    {
      id: "qualification",
      label: "Educational Qualification",
      type: "select",
      required: true,
      ocrSupported: false,
      placeholder: "Select qualification",
      validation: { options: ["Below 8th", "8th Pass", "10th Pass", "12th Pass", "Graduate", "Post Graduate", "Others"] },
      step: 0,
    },
    {
      id: "mobile_number",
      label: "Mobile Number",
      type: "text",
      required: true,
      ocrSupported: false,
      placeholder: "10-digit mobile number",
      validation: { pattern: "^\\d{10}$", length: 10 },
      step: 0,
    },
    {
      id: "email",
      label: "Email Address",
      type: "email",
      required: false,
      ocrSupported: false,
      placeholder: "your.email@example.com",
      validation: { pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" },
      step: 0,
    },
    {
      id: "aadhaar_number",
      label: "Aadhaar Number",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "12-digit Aadhaar number",
      validation: { pattern: "^\\d{12}$", length: 12 },
      step: 0,
    },

    // ── Step 2: Address Details ───────────────────────────────────────────
    {
      id: "address_line1",
      label: "House No., Street / Locality",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "House no., street, locality",
      validation: { minLength: 5, maxLength: 150 },
      step: 1,
    },
    {
      id: "city",
      label: "City / Town / Village",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "City or village name",
      validation: { minLength: 2, maxLength: 60 },
      step: 1,
    },
    {
      id: "district",
      label: "District",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "District name",
      validation: { minLength: 2, maxLength: 50 },
      step: 1,
    },
    {
      id: "state",
      label: "State",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "Telangana",
      validation: { minLength: 2, maxLength: 40 },
      step: 1,
    },
    {
      id: "pin_code",
      label: "PIN Code",
      type: "text",
      required: true,
      ocrSupported: true,
      placeholder: "6-digit PIN code",
      validation: { pattern: "^\\d{6}$", length: 6 },
      step: 1,
    },

    // ── Step 3: Vehicle Class ─────────────────────────────────────────────
    {
      id: "vehicle_class",
      label: "Vehicle Class to Apply For",
      type: "select",
      required: true,
      ocrSupported: false,
      placeholder: "Select vehicle class",
      validation: { options: ["MCWG (Motorcycle With Gear)", "MCWOG (Motorcycle Without Gear / Scooter)", "LMV (Light Motor Vehicle — Car)", "LMV + MCWG (Car + Motorcycle)"] },
      step: 2,
    },
    {
      id: "rto_office",
      label: "RTO Office (Jurisdiction)",
      type: "text",
      required: true,
      ocrSupported: false,
      placeholder: "RTO office name (auto-assigned by address)",
      validation: { minLength: 3, maxLength: 80 },
      step: 2,
    },
    {
      id: "existing_ll",
      label: "Existing Learner Licence Number (if any)",
      type: "text",
      required: false,
      ocrSupported: false,
      placeholder: "Leave blank for first-time applicants",
      validation: { maxLength: 30 },
      step: 2,
    },
    {
      id: "physical_fitness",
      label: "Self-Declaration of Physical Fitness",
      type: "checkbox",
      required: true,
      ocrSupported: false,
      placeholder: "I declare that I am physically and mentally fit to drive",
      validation: { mustBeTrue: true },
      step: 2,
    },
  ],
};
