/**
 * Passport Application Form Schema
 * Based on actual Passport Seva portal form flow (screenshots analyzed)
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const passportSchema = {
  serviceName: "Passport Application",
  officialPortal: "https://www.passportindia.gov.in",
  disclaimer: "This is a SevaSetu application draft for reference only. Final submission must be done on the official Passport Seva portal.",
  formReference: "Passport Seva Form (Fresh / Reissue)",

  steps: [
    {
      id: "passport-type",
      title: "Passport Type",
      description: "Select type of application and passport booklet",
      fields: [
        { id: "applyingFor", label: "Applying for", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Fresh Passport", "Re-issue of Passport"], sourceHint: "", needsVerification: false },
        { id: "typeOfApplication", label: "Type of Application", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Normal", "Tatkaal"], sourceHint: "", needsVerification: false },
        { id: "bookletType", label: "Type of Passport Booklet", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["36 Pages", "60 Pages"], sourceHint: "", needsVerification: false },
      ],
    },
    {
      id: "applicant-details",
      title: "Applicant Details",
      description: "Personal information of the applicant",
      fields: [
        { id: "surname", label: "Surname", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "Enter surname / family name", validation: "lettersOnly", sourceHint: "Aadhaar/PAN", needsVerification: false },
        { id: "givenName", label: "Given Name", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "Enter given name (first + middle)", validation: "lettersOnly", sourceHint: "Aadhaar/PAN", needsVerification: false },
        { id: "knownByOtherName", label: "Are you known by any other name(s)?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "otherName", label: "Other Name (if yes)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Alias or other name", validation: "lettersOnly", sourceHint: "", needsVerification: false },
        { id: "changedName", label: "Have you ever changed your name?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "previousName", label: "Previous Name (if changed)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Previous name before change", validation: "lettersOnly", sourceHint: "", needsVerification: false },
        { id: "dateOfBirth", label: "Date of Birth", type: "date", required: true, ocrSupported: true, copyEnabled: true, placeholder: "DD/MM/YYYY", validation: "date", sourceHint: "Aadhaar/10th Cert", needsVerification: false },
        { id: "placeOfBirth", label: "Place of Birth (Village/Town/City)", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "City or town where born", validation: "text", sourceHint: "", needsVerification: false },
        { id: "placeOfBirthDistrict", label: "District of Birth", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "District", validation: "text", sourceHint: "", needsVerification: false },
        { id: "placeOfBirthState", label: "State of Birth", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "State / UT", validation: "text", sourceHint: "", needsVerification: false },
        { id: "gender", label: "Gender", type: "radio", required: true, ocrSupported: true, copyEnabled: true, placeholder: "", validation: "required", options: ["Male", "Female", "Transgender"], sourceHint: "Aadhaar", needsVerification: false },
        { id: "maritalStatus", label: "Marital Status", type: "select", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Select", validation: "required", options: ["Single/Unmarried", "Married", "Separated", "Divorced", "Widow/Widower"], sourceHint: "", needsVerification: false },
        { id: "citizenshipBy", label: "Citizenship of India by", type: "select", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Select", validation: "required", options: ["Birth", "Descent", "Registration/Naturalization"], sourceHint: "", needsVerification: false },
        { id: "panNumber", label: "PAN (if available)", type: "text", required: false, ocrSupported: true, copyEnabled: true, placeholder: "ABCDE1234F", validation: "pan", sourceHint: "PAN Card", needsVerification: false },
        { id: "voterIdNumber", label: "Voter ID (if available)", type: "text", required: false, ocrSupported: true, copyEnabled: true, placeholder: "Voter ID / EPIC number", validation: "text", sourceHint: "Voter ID", needsVerification: false },
        { id: "employmentType", label: "Employment Type", type: "select", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Select", validation: "required", options: ["Government", "Statutory Body", "PSU", "Private", "Self Employed", "Homemaker", "Student", "Retired", "Not Employed", "Others"], sourceHint: "", needsVerification: false },
        { id: "parentSpouseGovServant", label: "Is parent/spouse a Government Servant?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "educationalQualification", label: "Educational Qualification", type: "select", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Select", validation: "required", options: ["Below Matriculate", "Matriculate", "Senior Secondary", "Graduate and Above", "Professional Degree"], sourceHint: "", needsVerification: false },
        { id: "nonEcrEligible", label: "Eligible for Non-ECR category?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: true },
        { id: "distinguishingMark", label: "Visible/Distinguishing Mark", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "e.g. Mole on right cheek", validation: "text", sourceHint: "", needsVerification: false },
        { id: "aadhaarNumber", label: "Aadhaar Number (if available)", type: "text", required: false, ocrSupported: true, copyEnabled: true, placeholder: "12-digit Aadhaar", validation: "aadhaar", sourceHint: "Aadhaar Card", needsVerification: false },
      ],
    },
    {
      id: "family-details",
      title: "Family Details",
      description: "Details of parents and spouse",
      fields: [
        { id: "fatherGivenName", label: "Father's Given Name", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "Father's first + middle name", validation: "lettersOnly", sourceHint: "Aadhaar/10th Cert", needsVerification: false },
        { id: "fatherSurname", label: "Father's Surname", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "Father's surname", validation: "lettersOnly", sourceHint: "Aadhaar/10th Cert", needsVerification: false },
        { id: "motherGivenName", label: "Mother's Given Name", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Mother's first + middle name", validation: "lettersOnly", sourceHint: "", needsVerification: false },
        { id: "motherSurname", label: "Mother's Surname", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Mother's surname", validation: "lettersOnly", sourceHint: "", needsVerification: false },
        { id: "spouseGivenName", label: "Spouse's Given Name (if married)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Spouse first name", validation: "lettersOnly", sourceHint: "", needsVerification: false },
        { id: "spouseSurname", label: "Spouse's Surname (if married)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Spouse surname", validation: "lettersOnly", sourceHint: "", needsVerification: false },
        { id: "fatherPassportNo", label: "Father's Passport Number (if any)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Father's passport number", validation: "text", sourceHint: "", needsVerification: true },
        { id: "motherPassportNo", label: "Mother's Passport Number (if any)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Mother's passport number", validation: "text", sourceHint: "", needsVerification: true },
      ],
    },
    {
      id: "address-details",
      title: "Address Details",
      description: "Present and permanent residential address",
      fields: [
        { id: "presentAddressAbroad", label: "Is present address out of India?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "houseStreet", label: "House No. and Street Name", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "House/Flat no., Street, Locality", validation: "text", sourceHint: "Aadhaar/Address Proof", needsVerification: false },
        { id: "city", label: "Village/Town/City", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "City or town name", validation: "text", sourceHint: "Aadhaar", needsVerification: false },
        { id: "state", label: "State/UT", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "State", validation: "text", sourceHint: "Aadhaar", needsVerification: false },
        { id: "district", label: "District", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "District", validation: "text", sourceHint: "Aadhaar", needsVerification: false },
        { id: "policeStation", label: "Police Station", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Nearest police station", validation: "text", sourceHint: "", needsVerification: true },
        { id: "pinCode", label: "PIN Code", type: "text", required: true, ocrSupported: true, copyEnabled: true, placeholder: "6-digit PIN", validation: "pincode", sourceHint: "Aadhaar", needsVerification: false },
        { id: "mobileNumber", label: "Mobile Number", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "10-digit mobile", validation: "mobile", sourceHint: "", needsVerification: false },
        { id: "telephoneNumber", label: "Telephone Number", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Landline with STD code", validation: "text", sourceHint: "", needsVerification: false },
        { id: "emailId", label: "Email ID", type: "email", required: true, ocrSupported: false, copyEnabled: true, placeholder: "your.email@example.com", validation: "email", sourceHint: "", needsVerification: false },
        { id: "permanentAddressAvailable", label: "Is permanent address available?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "permanentSameAsPresent", label: "Permanent address same as present?", type: "radio", required: false, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
      ],
    },
    {
      id: "emergency-contact",
      title: "Emergency Contact",
      description: "Person to contact in case of emergency",
      fields: [
        { id: "emergencyName", label: "Emergency Contact Name & Address", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "Full name and address of contact person", validation: "text", sourceHint: "", needsVerification: false },
        { id: "emergencyMobile", label: "Emergency Mobile Number", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "10-digit mobile", validation: "mobile", sourceHint: "", needsVerification: false },
        { id: "emergencyTelephone", label: "Telephone Number", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Landline if available", validation: "text", sourceHint: "", needsVerification: false },
        { id: "emergencyEmail", label: "Email ID", type: "email", required: false, ocrSupported: false, copyEnabled: true, placeholder: "Contact email", validation: "email", sourceHint: "", needsVerification: false },
      ],
    },
    {
      id: "previous-passport",
      title: "Previous Passport Details",
      description: "Details of previously held passport (if any)",
      fields: [
        { id: "heldPassportBefore", label: "Have you ever held/applied for a passport?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "oldPassportNumber", label: "Old Passport Number", type: "text", required: false, ocrSupported: true, copyEnabled: true, placeholder: "Previous passport number", validation: "text", sourceHint: "Old Passport", needsVerification: false },
        { id: "oldPassportDateOfIssue", label: "Date of Issue", type: "date", required: false, ocrSupported: true, copyEnabled: true, placeholder: "DD/MM/YYYY", validation: "date", sourceHint: "Old Passport", needsVerification: false },
        { id: "oldPassportPlaceOfIssue", label: "Place of Issue", type: "text", required: false, ocrSupported: true, copyEnabled: true, placeholder: "Place where old passport was issued", validation: "text", sourceHint: "Old Passport", needsVerification: false },
        { id: "oldPassportFileNumber", label: "File Number (if available)", type: "text", required: false, ocrSupported: false, copyEnabled: true, placeholder: "File number from old passport", validation: "text", sourceHint: "", needsVerification: true },
      ],
    },
    {
      id: "other-details",
      title: "Other Details",
      description: "Criminal/legal proceedings and passport history",
      fields: [
        { id: "criminalProceedings", label: "Criminal proceedings pending?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "warrantSummons", label: "Arrest warrant or summons pending?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "convictedByCourt", label: "Convicted by court in last 5 years?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "passportRefused", label: "Passport ever refused/denied?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "passportImpounded", label: "Passport impounded/revoked?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "politicalAsylum", label: "Applied for political asylum?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "returnedOnEC", label: "Returned to India on Emergency Certificate?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
        { id: "deportedRepatriated", label: "Deported/Repatriated from any country?", type: "radio", required: true, ocrSupported: false, copyEnabled: true, placeholder: "", validation: "required", options: ["Yes", "No"], sourceHint: "", needsVerification: false },
      ],
    },
    {
      id: "self-declaration",
      title: "Self Declaration",
      description: "Declaration and verification",
      fields: [
        { id: "declarationAccepted", label: "I hereby declare that all information is true and correct", type: "checkbox", required: true, ocrSupported: false, copyEnabled: false, placeholder: "", validation: "mustBeTrue", sourceHint: "", needsVerification: false },
        { id: "declarationPlace", label: "Place", type: "text", required: true, ocrSupported: false, copyEnabled: true, placeholder: "City where signing", validation: "text", sourceHint: "", needsVerification: false },
        { id: "declarationDate", label: "Date", type: "date", required: true, ocrSupported: false, copyEnabled: true, placeholder: "DD/MM/YYYY", validation: "date", sourceHint: "", needsVerification: false },
      ],
    },
    {
      id: "review-download",
      title: "Review & Download",
      description: "Review your complete draft and download PDF",
      fields: [],
    },
  ],
};
